// Headless tests for src/IconEdit.cpp -- the on-disk edits behind the
// context menu's Rename. Not part of the autotools build; run by hand
// after a normal build (src/defaults.h is generated by it):
//
//   g++ -Isrc tests/IconEditTest.cpp src/IconEdit.cpp src/Database.cpp \
//       src/Misc.cpp $(pkg-config --cflags --libs glib-2.0 gio-2.0) \
//       -o /tmp/IconEditTest && /tmp/IconEditTest
//
// Works in /tmp/ietest and exits non-zero if any check fails.
#include "IconEdit.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <sys/stat.h>
#include <unistd.h>
using namespace std;

static int fails = 0;
#define CHECK(cond, msg) do { if (cond) cout << "PASS: " << msg << "\n"; else { cout << "FAIL: " << msg << "\n"; fails++; } } while (0)

static string slurp(const string & p) { ifstream f(p.c_str()); stringstream ss; ss << f.rdbuf(); return ss.str(); }
static void put(const string & p, const string & c) { ofstream f(p.c_str()); f << c; }
static bool has(const string & hay, const string & needle) { return hay.find(needle) != string::npos; }
static bool exists(const string & p) { struct stat st; return lstat(p.c_str(), &st) == 0; }

int main()
{
    system("rm -rf /tmp/ietest && mkdir -p /tmp/ietest");
    string err;

    // 1. .lnk caption, with UTF-8, other fields untouched
    put("/tmp/ietest/a.lnk", "table Icon\n  Caption: Old\n  Command: true\n  X: 5\n  Y: 6\nend\n");
    bool ok = setLnkCaption("/tmp/ietest/a.lnk", "M\xC3\xBAsica \xC3\xB1", err);
    string c = slurp("/tmp/ietest/a.lnk");
    CHECK(ok, "lnk: setLnkCaption succeeds");
    CHECK(has(c, "Caption: M\xC3\xBAsica \xC3\xB1"), "lnk: UTF-8 caption stored byte-exact");
    CHECK(has(c, "Command: true") && has(c, "X: 5") && has(c, "Y: 6"), "lnk: other fields intact");
    CHECK(!has(c, "Caption: Old"), "lnk: old caption gone");

    // 2. .desktop with several traps
    string d =
        "# Name=NotThisOne\n"
        "[Desktop Entry]\n"
        "Type=Application\n"
        "Name=Old\n"
        "Name[es]=Viejo\n"
        "Exec=foo\n"
        "\n"
        "[Desktop Action new]\n"
        "Name=New Window\n"
        "Exec=foo --new\n";
    put("/tmp/ietest/b.desktop", d);
    chmod("/tmp/ietest/b.desktop", 0755);
    ok = setDesktopName("/tmp/ietest/b.desktop", "A\xC3\xB1o", err);
    c = slurp("/tmp/ietest/b.desktop");
    CHECK(ok, "desktop: setDesktopName succeeds");
    CHECK(has(c, "\nName=A\xC3\xB1o\n"), "desktop: Name= replaced with UTF-8 value");
    CHECK(!has(c, "Name=Old"), "desktop: old Name= gone");
    CHECK(has(c, "Name[es]=Viejo"), "desktop: localized Name[es]= preserved");
    CHECK(has(c, "Name=New Window"), "desktop: Name= in [Desktop Action] preserved");
    CHECK(has(c, "# Name=NotThisOne"), "desktop: comment containing Name= preserved");
    CHECK(has(c, "Exec=foo --new"), "desktop: other group's Exec preserved");
    struct stat st; stat("/tmp/ietest/b.desktop", &st);
    CHECK((st.st_mode & 07777) == 0755, "desktop: file mode 0755 preserved");
    CHECK(!exists("/tmp/ietest/b.desktop.idesk-tmp"), "desktop: no temp file left behind");

    // 3. .desktop with no Name= gets one right after the header
    put("/tmp/ietest/c.desktop", "[Desktop Entry]\nType=Application\nExec=foo\n");
    ok = setDesktopName("/tmp/ietest/c.desktop", "X", err);
    c = slurp("/tmp/ietest/c.desktop");
    CHECK(ok && c.find("Name=X") != string::npos && c.find("Name=X") < c.find("Type="),
          "desktop: missing Name= inserted right after the header");

    // 4. no [Desktop Entry] at all: refuse, file untouched
    put("/tmp/ietest/d.desktop", "Type=Application\nName=Z\n");
    ok = setDesktopName("/tmp/ietest/d.desktop", "Q", err);
    CHECK(!ok && !err.empty() && slurp("/tmp/ietest/d.desktop") == "Type=Application\nName=Z\n",
          "desktop: no [Desktop Entry] group is refused and file untouched");

    // 5. symlinks refused, target untouched
    system("ln -s /tmp/ietest/a.lnk /tmp/ietest/link.lnk");
    string before = slurp("/tmp/ietest/a.lnk");
    ok = setLnkCaption("/tmp/ietest/link.lnk", "Hacked", err);
    CHECK(!ok && slurp("/tmp/ietest/a.lnk") == before, "lnk: symlink refused, target untouched");
    system("ln -s /tmp/ietest/b.desktop /tmp/ietest/link.desktop");
    before = slurp("/tmp/ietest/b.desktop");
    ok = setDesktopName("/tmp/ietest/link.desktop", "Hacked", err);
    CHECK(!ok && slurp("/tmp/ietest/b.desktop") == before && exists("/tmp/ietest/link.desktop"),
          "desktop: symlink refused, target untouched, link still a link");

    // 6. missing .lnk does not kill the process (Database would _exit)
    ok = setLnkCaption("/tmp/ietest/nope.lnk", "x", err);
    CHECK(!ok && !err.empty(), "lnk: missing file returns an error instead of exiting");

    // 7. plain file rename
    put("/tmp/ietest/notas.txt", "hola");
    string np;
    ok = renamePlainFile("/tmp/ietest/notas.txt", "ideas.txt", np, err);
    CHECK(ok && np == "/tmp/ietest/ideas.txt", "file: rename succeeds and reports the new absolute path");
    CHECK(exists("/tmp/ietest/ideas.txt") && !exists("/tmp/ietest/notas.txt"), "file: old gone, new present");
    CHECK(slurp("/tmp/ietest/ideas.txt") == "hola", "file: content preserved");

    // 8. collision refused, both survive
    put("/tmp/ietest/other.txt", "otro");
    ok = renamePlainFile("/tmp/ietest/ideas.txt", "other.txt", np, err);
    CHECK(!ok && !err.empty(), "file: rename onto an existing name refused");
    CHECK(slurp("/tmp/ietest/other.txt") == "otro" && exists("/tmp/ietest/ideas.txt"), "file: both files survive a refused rename");

    // 9. invalid name
    ok = renamePlainFile("/tmp/ietest/ideas.txt", "a/b.txt", np, err);
    CHECK(!ok && exists("/tmp/ietest/ideas.txt"), "file: name containing / refused");

    // 10. a folder
    system("mkdir /tmp/ietest/carpeta");
    ok = renamePlainFile("/tmp/ietest/carpeta", "carpeta2", np, err);
    CHECK(ok && exists("/tmp/ietest/carpeta2") && !exists("/tmp/ietest/carpeta"), "file: folders rename too");

    // 11. generic keys, as used by Properties
    put("/tmp/ietest/g.desktop",
        "[Desktop Entry]\nType=Application\nName=G\nExec=foo %U\nIcon=old\n"
        "\n[Desktop Action x]\nExec=bar\nIcon=other\n");
    string v;
    CHECK(getDesktopKey("/tmp/ietest/g.desktop", "Exec", v) && v == "foo %U", "key: Exec read raw, field codes kept");
    CHECK(getDesktopKey("/tmp/ietest/g.desktop", "Icon", v) && v == "old", "key: Icon read from [Desktop Entry] only");
    CHECK(!getDesktopKey("/tmp/ietest/g.desktop", "Comment", v) && v.empty(), "key: missing key reported");
    ok = setDesktopKey("/tmp/ietest/g.desktop", "Exec", "baz --x %F", err);
    c = slurp("/tmp/ietest/g.desktop");
    CHECK(ok && has(c, "\nExec=baz --x %F\n") && has(c, "Exec=bar") && has(c, "Icon=other"), "key: Exec replaced, other group untouched");
    ok = setDesktopKey("/tmp/ietest/g.desktop", "Comment", "hi", err);
    CHECK(ok && getDesktopKey("/tmp/ietest/g.desktop", "Comment", v) && v == "hi", "key: absent key added");
    put("/tmp/ietest/k.lnk", "table Icon\n  Caption: C\n  Command: true\n  Icon: /a.png\nend\n");
    bool isArr = true;
    CHECK(getLnkKey("/tmp/ietest/k.lnk", "Command", v, isArr) && v == "true" && !isArr, "lnk key: Command read");
    ok = setLnkKey("/tmp/ietest/k.lnk", "Icon", "/b.png", err);
    CHECK(ok && getLnkKey("/tmp/ietest/k.lnk", "Icon", v, isArr) && v == "/b.png", "lnk key: Icon replaced");
    put("/tmp/ietest/m.lnk", "table Icon\n  Caption: M\n  Command[0]: a\n  Command[1]: b\nend\n");
    CHECK(getLnkKey("/tmp/ietest/m.lnk", "Command", v, isArr) && isArr && v == "a", "lnk key: command list flagged as array");
    system("ln -s /tmp/ietest/g.desktop /tmp/ietest/gl.desktop");
    ok = setDesktopKey("/tmp/ietest/gl.desktop", "Name", "X", err);
    CHECK(!ok && !err.empty() && !has(slurp("/tmp/ietest/g.desktop"), "Name=X"), "key: symlink refused, target untouched");

    // 12. per-icon tooltip keys, as Properties writes them
    ok = setDesktopKey("/tmp/ietest/g.desktop", "X-Idesk-Tooltip-Enabled", "false", err);
    CHECK(ok && getDesktopKey("/tmp/ietest/g.desktop", "X-Idesk-Tooltip-Enabled", v) && v == "false", "tooltip: .desktop switch written");
    ok = setLnkKey("/tmp/ietest/k.lnk", "X-Idesk-Tooltip-Enabled", "false", err);
    CHECK(ok && getLnkKey("/tmp/ietest/k.lnk", "X-Idesk-Tooltip-Enabled", v, isArr) && v == "false", "tooltip: .lnk switch written (same key as .desktop)");
    ok = setLnkKey("/tmp/ietest/k.lnk", "ToolTip.Caption", "Un tip", err);
    c = slurp("/tmp/ietest/k.lnk");
    CHECK(ok && has(c, "ToolTip.Caption: Un tip") && has(c, "Caption: C"), "tooltip: .lnk text written, caption intact");

    // 13. .lnk tooltip text: Comment:, with the old ToolTip.Caption: still read
    put("/tmp/ietest/t1.lnk", "table Icon\n  Caption: T\n  Command: true\n  ToolTip.Caption: Viejo\nend\n");
    CHECK(getLnkTooltip("/tmp/ietest/t1.lnk", v) && v == "Viejo", "comment: old ToolTip.Caption still read");
    put("/tmp/ietest/t2.lnk", "table Icon\n  Caption: T\n  Command: true\n  Comment: Nuevo\nend\n");
    CHECK(getLnkTooltip("/tmp/ietest/t2.lnk", v) && v == "Nuevo", "comment: Comment: read");
    put("/tmp/ietest/t3.lnk", "table Icon\n  Caption: T\n  Command: true\n  Comment: Gana\n  ToolTip.Caption: Pierde\nend\n");
    CHECK(getLnkTooltip("/tmp/ietest/t3.lnk", v) && v == "Gana", "comment: Comment: wins over the old key");
    ok = setLnkKey("/tmp/ietest/t1.lnk", "Comment", "Editado \xC3\xB1", err);
    c = slurp("/tmp/ietest/t1.lnk");
    CHECK(ok && has(c, "Comment: Editado \xC3\xB1") && !has(c, "ToolTip.Caption") && !has(c, "Viejo"),
          "comment: writing Comment: drops the old ToolTip.Caption");
    CHECK(has(c, "Caption: T") && has(c, "Command: true"), "comment: other keys intact");
    ok = setLnkKey("/tmp/ietest/t1.lnk", "Comment", "", err);
    CHECK(ok && getLnkTooltip("/tmp/ietest/t1.lnk", v) && v.empty(), "comment: clearing the text does not bring the old one back");
    put("/tmp/ietest/t4.lnk", "table Icon\n  Caption: T\n  Command: true\nend\n");
    CHECK(getLnkTooltip("/tmp/ietest/t4.lnk", v) && v.empty(), "comment: no tooltip at all reads as empty");
    CHECK(!getLnkTooltip("/tmp/ietest/nope.lnk", v), "comment: unreadable file reported");

    cout << (fails == 0 ? "ALL PASSED" : "SOME FAILED") << " (" << fails << " failures)\n";
    return fails;
}
